permissions:
  - name: "organization:create"
    description: "Create new organizations."
  - name: "organization:read"
    description: "Read organization details or lists."
  - name: "organization:update"
    description: "Update organization details."
  - name: "organization:delete"
    description: "Delete organizations."
  - name: "user:read"
    description: "Read user details or lists (within organization or self)."
  - name: "user:update"
    description: "Update other users' details (admin)."
  - name: "user:update:self"
    description: "Update own user details."
  - name: "user:delete"
    description: "Delete other users (admin)."
  - name: "user:delete:self"
    description: "Delete own user."
  - name: "user:assign:organization"
    description: "Add/remove users from organizations."
  - name: "user:assign:role"
    description: "Add/remove roles from users."
  - name: "user:assign:policy"
    description: "Add/remove policies from users."
  - name: "role:create"
    description: "Create roles in an organization."
  - name: "role:read"
    description: "Read role details or lists."
  - name: "role:update"
    description: "Update roles."
  - name: "role:delete"
    description: "Delete roles."
  - name: "role:assign"
    description: "Assign/remove roles to/from users."
  - name: "permission:create"
    description: "Create new permissions."
  - name: "permission:read"
    description: "Read permission details or lists."
  - name: "permission:update"
    description: "Update permissions."
  - name: "permission:delete"
    description: "Delete permissions."
  - name: "permission:assign"
    description: "Assign/remove permissions to roles/users."
  - name: "policy:create"
    description: "Create ABAC policies."
  - name: "policy:read"
    description: "Read policy details or lists."
  - name: "policy:update"
    description: "Update policies."
  - name: "policy:delete"
    description: "Delete policies."

organization_types:
  - name: "Company"
    description: "Business organization with multiple members and formal structure."
  - name: "Individual"
    description: "Personal organization for individual users and small projects."
  - name: "Enterprise"
    description: "Large-scale enterprise organization with complex hierarchies and advanced features."

application_types:
  - name: "NodeJS"
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine for server-side applications."
  - name: "Laravel"
    description: "PHP web application framework with expressive, elegant syntax."
  - name: "PHP"
    description: "Popular general-purpose scripting language especially suited for web development."
  - name: "React"
    description: "JavaScript library for building user interfaces with component-based architecture."
  - name: "Vue.js"
    description: "Progressive JavaScript framework for building user interfaces and single-page applications."