apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: uptime-dev
  labels:
    app: api-gateway
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        environment: development
    spec:
      containers:
      - name: api-gateway
        image: uptime/api-gateway:dev
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_GATEWAY_PORT
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: uptime-dev
  labels:
    app: api-gateway
    environment: development
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: LoadBalancer